replicaCount: 1
image:
  repository: us-central1-docker.pkg.dev/project-40d105bf-bb2b-4bf6-b9f/golden-path/golden-path-microservice
  tag: 48a861d2154a
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
gcp:
  projectId: project-40d105bf-bb2b-4bf6-b9f
  region: us-central1-a
  clusterName: golden-path-dev
serviceAccount:
  create: true
  name: golden-path-microservice
  annotations:
    iam.gke.io/gcp-service-account: golden-path-workload@project-40d105bf-bb2b-4bf6-b9f.iam.gserviceaccount.com
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations:
    cloud.google.com/backend-config: '{"default":"golden-path-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
backendConfig:
  enabled: true
  name: golden-path-backend-config
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /healthz
    port: 8080
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: golden-path-ip
  hosts:
    - host: gcp.lovelu.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
env:
  SERVICE_NAME: golden-path-microservice
  ENVIRONMENT: dev
externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStoreName: gcp-secret-store
  databasePasswordSecretName: golden-path-dev-database-password
networkPolicy:
  enabled: true
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
