apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: cart-payment-service-mtls
  namespace: golden-path
spec:
  host: cart-payment-service.golden-path.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
