apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: golden-path-default-telemetry
  namespace: golden-path
spec:
  metrics:
    - providers:
        - name: prometheus
  accessLogging:
    - providers:
        - name: envoy
