{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cart-payment-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cart.labels" . | nindent 4 }}
spec:
  refreshPolicy: Periodic
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: cart-payment-db
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.databasePasswordSecretName }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
