{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "order.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus-stack
    {{- include "order.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "order.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
