{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.gcp.region | quote }}
          clusterName: {{ .Values.gcp.clusterName | quote }}
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: golden-path-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  refreshPolicy: Periodic
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: golden-path-db
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.databasePasswordSecretName }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
{{- end }}
