apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart-payment-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ashequrrasul/gcp-golden-path-platform.git
    targetRevision: main
    path: helm-charts/cart-payment-service
    helm:
      releaseName: cart-payment-service
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: golden-path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
