apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ashequrrasul/gcp-golden-path-deploy.git
    targetRevision: main
    path: helm/frontend
    helm:
      releaseName: ecommerce-frontend
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: golden-path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
