{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: order-db
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.databasePasswordSecretName }}
{{- end }}
